### ISSUE TITLE
Not found keys.js

### ISSUE THREAD

**Issue by kris-development** [interfaced/zombiebox-demo#10]
Не находит файл: node_modules/zombiebox/zb/device/input/keys.js
В каталоге лежит key.js
Переименуйте пожалуйста

**Comment by l1bbcsg** [comment]
`key.js` – корректное название этого файла, он был переименован достаточно давно с сохранением обратной совместимости и недавно старый `keys.js` удалён совсем.

Актуализировали зависимости демо до свежих версий в `2.0.2` и обновили пути, проблема должна решится.
