### ISSUE TITLE
App Subtitle on WebOS

### ISSUE THREAD

**Issue by tiorobby** [interfaced/zombiebox-demo#11]
Hi Again....
I want to ask you something very little but I want to fix it in the right way.
When I test the app on the WebOS emulator and TV, the app "Subtitle" (at the icon app bottom on LG launch and in the main title) says "my_app_name | ZombieBox".
I tried to set the app subtitle in the appinfo and application files but no success. 

My question: how can I change that app subtitle?

![zb-01](https://user-images.githubusercontent.com/1233434/86539473-9de62b80-beca-11ea-9128-cc7d350e1145.jpeg)

**Comment by trave** [comment]
Hello,
As said in webOS docs: http://webostv.developer.lge.com/develop/app-developer-guide/app-metadata/
> You can use the HTML <title> element in your app for the subtitle. The app version or vendor name is recommended for the subtitle.

You can change this value by replacing builtin template node_modules/zombiebox/templates/index.html.tpl with your own.
1. Copy the original template to %PROJECT%/templates/index.html.tpl;
2. Replace <title> content with your data;
3. Add/Change `templates` field in your project config.js by adding your `templates` dir like this: `templates: [ path.join(__dirname, 'templates') ],`;
4. Build an app and now your string will be displayed in app subtitle.
