### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ghost** [interfaced/zombiebox-demo#2]
Здравствуйте.
Возникли проблемы при сборке проекта

project/node_modules/zombiebox/lib/zb.js:117
		if (!customConfigs.length) {
		                   ^

TypeError: Cannot read property 'length' of undefined
    at new ZBApplication (/home/sasha/code/project/node_modules/zombiebox/lib/zb.js:117:22)
    at Function.createInstanceFromPath (/home/sasha/code/project/node_modules/zombiebox/lib/zb.js:908:10)
    at Function.getCLI (/home/sasha/code/project/node_modules/zombiebox/lib/zb.js:917:29)
    at runZB (/usr/local/lib/node_modules/zombiebox-cli/bin/zb.js:93:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/zombiebox-cli/bin/zb.js:112:2)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

Подскажите как решить проблему?

**Comment by l1bbcsg** [comment]
Здравствуйте!

Уточните, пожалуйста, какую версию приложения Вы собираете и какой командой?

Также рекомендуем убедиться что все зависимости актуальных версий (`rm -rf node_modules && npm i`)

**Comment by ghost** [comment]
https://zombiebox.tv/doc.html#section-2
Следовала строго по инструкции:
npm -g install zombiebox-cli
zb init
npm install
zb run - после этой команды ошибка.

**Comment by l1bbcsg** [comment]
Похоже, проблемы в пакете команд `zombiebox-cli`. Мы планируем их решить к следующему релизу.

Пока в качестве решения можно использовать команды из локального пакета вместо глобального, например с помощью [npx](https://www.npmjs.com/package/npx): `npx zombiebox run` или без него: `./node_modules/zombiebox/bin/zb.js run`

**Comment by ghost** [comment]
Попробовала с командами npx zombiebox run, ./node_modules/zombiebox/bin/zb.js run

./node_modules/zombiebox/bin/zb.js run
Extension about loaded
Extension dependency-injection loaded
Extension i18n loaded
Extension ui loaded
Platform pc loaded
Platform samsung loaded
[WARN] Configuration key scripts with type Array is deprecated, use compilation.include instead
Open http://localhost:1337/

На самой странице: Не удается получить доступ к сайту

При команде npx zombiebox всё тоже самое, но страница получается просто пустая.

**Comment by ghost** [comment]
При npx zombiebox run консоль браузера выдает ошибки:
Uncaught SyntaxError: The requested module '/modules/samsung/device' does not provide an export named 'default'
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by bigvc** [comment]
Если к демо т.е этому проекту добавить платформу, например samsung 
`npm i zombiebox-platform-samsung --save`

` npx zombiebox run` запускает проект, но в браузере ошибка SyntaxError: The requested module '/modules/samsung/device' does not provide an export named 'default'

Используя zb, вообще не получается завести проект по документации с https://www.npmjs.com/package/zombiebox
Ошибки такие же как и в первом сообщении.

**Comment by tadjik1** [comment]
@aleksandra-tk @bigvc похоже у вас проблемы с версиями библиотек. все, что вы устанавливаете с `npm i -g` содержит версию 1, тогда как в этом приложении уже используется следующая, вторая версия.

попробуйте сделать
```
rm -rf node_modules
npm install
npm start
```

мне помогло
