### ISSUE TITLE
i have a problem running the application on webos emulator

### ISSUE THREAD

**Issue by mostafa-raafat** [interfaced/zombiebox-demo#6]
after add this section to config.js
```
webos: {
				toolsDir: '/opt/webOS_TV_SDK/CLI/bin/',
				appinfo: {
					id: 'com.myco.app.appname',
					title: 'AppName',
					main: 'index.html',
					type: 'web',
					vendor: 'My Company',
					version: '1.0.0',
					appDescription: 'This is an app tagline',
					resolution: '1920x1080',
					bgColor: 'red',
					iconColor: 'red',
					transparent: false
				}
			}
```
i and build for web os everything seams to be Good 
i have com.myco.app.appname_1.0.0_all.ipk 
when i try to open the application on emulator i get a blank black screen 
that app seams to be working fine on the browser localhost 
but for emulator not working

**Comment by l1bbcsg** [comment]
Can you share more details on what's going wrong? A stack trace or any errors that occur?

Without details I would assume it's an error in emulator. They are not very good at actually emulating TVs missing a lot of platforms APIs and have different behaviour in addition to being simply unstable. Internally we avoid using emulators and instead develop using pc platform and test on real devices. Device specific problems can typically only be detected on real hardware anyway and emulators end up being an extra unnecessary step and an extra platform to support.
