### ISSUE TITLE
Navigation and Resolution Issues

### ISSUE THREAD

**Issue by tiorobby** [interfaced/zombiebox-demo#8]
Hi Guys,
first of all i want to say congratulations for your project. It's seems to be a very good framework for smart tv apps development.

I have just know your project few weeks ago and i have some questions about how to do some basic things in order to test the demo project. I was testing this project on WebOS

1.- Can you can help me about how to add the onclick event to any element of the base list item? In the demo, those elements are divs with some text inside (id) and I want to add some navigation: for example go to the "video-player" scene when I click on any element. Currently I tried to add an event listener to the div (in the widget js) but this click works only on the "local server" testing (npm start), not with the ENTER button of the smart tv remote control.

2.- The second issue is about the resolution . I build de Webos ipk package, tried it on the emulator and on a real tv and always the project doesn't fit de full screen resolution. Where do I have to change values in order the app fit the full screen of the emulator or the smart tv?

Thanks in advance for your help and if you have any documentation of the proyect it would be very helpful.

**Comment by l1bbcsg** [comment]
Hello, thank you for your interest in ZombieBox.

ZombieBox focus and navigation works on widgets level, not DOM level.
In general to handle clicks and other input you should use widget events and not DOM as those are made cross platform unlike DOM key codes and integrated with navigation and focus management.
In case of BaseList, the list is the widget but all individual items are not. To handle item clicks, use `EVENT_CLICK` from `BaseList` on the list itself, for example in demo:

```js
const list = this._exported.baseList;

list.on(list.EVENT_CLICK, (event, data) => {
	if (data.id === 2) {
		// Clicked button 2
		// data is the same data associated DataList item had
	}
});

```

**Comment by l1bbcsg** [comment]
App resolution depends on several factors:
* TV OSD resolution for a particular device (note that it's different from panel size and max video resolution), this page has details on supported by webOS app resolutions: http://webostv.developer.lge.com/discover/specifications/supported-app-resolution/
* App resolution as detected and applied by `Application._appendScreenSizeClass`.
* Resolution set in webOS [app metadata](http://webostv.developer.lge.com/develop/app-developer-guide/app-metadata/) (appinfo.json), as configured by `platforms.webos.appinfo.resolution` app config field, see [webOS package docs](https://github.com/interfaced/zombiebox-platform-webos/blob/master/DOCS.md#config-options).

Can you tell exactly what each of those are set to?

If I had to guess without additional info, I suspect your ZombieBox application is set to HD, app CSS styles deal with HD, but appinfo resolution is either set to FullHD or missing this field and by default your TV assumes FullHD.

Documentation is still work in progress, we're adding coverage to new features and trying to cover existing as well, but it's not an easy endeavour.

**Comment by tiorobby** [comment]
Thanks a lot for your help about my issues!!
All you said was very helpful....

In fact, the resolution tips and your guess was totally right. I set the resolution in the webos configs and all worked. Now I have a realease (close to an mvp but not an mvp yet) and worked perfect on emulator and tv.

Here the example
https://youtu.be/LQfAwk7NmnI
