### ISSUE TITLE
Cutejs: displaying data in scene

### ISSUE THREAD

**Issue by tiorobby** [interfaced/zombiebox-demo#9]
Hi again.
now I have problems displaying data in scenes.
My first thought was saving the data in _exported. So I tried to replace content to the title var with:

`text(this._exported.title, some_var);`

The title changed to the value I needed so I declare 2 more values in _exported to display them in the same way with the cutejs notation.

Looking on the cutejs readme I found that I have to put a div with the data-export-id attribute in order to render my info.

<div data-export-id="{{@title}}"></div>

But, Which is the correct way to print the saved value (_exported) in the src attribute of an <img> tag inside a jst file? I tried to use {{- this.my_var_in_exported}} or some like that but is not the right  way to use it Maybe I'm missing something due to my lack of experience using cutejs.

If you could help me I'd appreciate it.

Thanks a lot!

**Comment by l1bbcsg** [comment]
`_exported` is a dictionary containing nodes exported by CuteJS template, this is meant for manipulation of rendered DOM.

If you want to pass data to template, you need to use template params. Each generated CuteJS template exports 3 variables: `In`, `Out` and `render`. The first two are typedefs for params and exported data respectively while the third is the function that accepts `In` and produces `Out`, `Out` instance is typically stored in `_exported`. Template classes themselves are generated from `jst` files in runtime.

First, you need to declare type of your params in template with `{{* this.name type}}` notation. 

Then pass it as the parameter to `render`. `AbstractCuteScene`, `AbstractCuteWidget` and their descendants have `_renderTemplate` and `_getTemplateData` hooks for convenience (but you can also just use `render` as you see fit if you're not inheriting from those).

Then you can use it with either `{{- this.name}}` or `{{= this.name}}` in jst template.

widget.jst
```
{{* this.imageUrl string }}

<img src="{{= this.imageUrl}}"/>
```

widget.js
```
import AbstractCuteWidget from 'cutejs/widgets/abstract-widget';
import {In, Out, render} from 'generated/project/path/to/widget.jst.js';

export default class Widget extends AbstractCuteWidget {
	constructor() {
		super();

		/**
		 * @type {Out}
		 * @protected
		 */
		this._exported;
	}

	/**
	 * @override
	 */
	_renderTemplate() {
		return render(this._getTemplateData(), this._getTemplateOptions());
	}

	/**
	 * @return {In}
	 * @override
	 */
	_getTemplateData() {
		return {
			imageUrl: 'https://placekitten.com/200/300'
		}
	}
}
```

Such variables are defined statically and rendered only when the template (`render` or `_renderTemplate`) is re-invoked. If you want to update the values dynamically, the best course of action is to export the node with `data-exported-id`, access it through `exported` and update it with DOM api (`setAttribute('src', value)` et al)
